### PR TITLE
Replace eot font file with version from the slick repo.

### PR DESCRIPTION
**Pull request by TechFounder**
Hi, it looks like replacing just the eot with the current version that resides at the slick repo makes the error go away. Thanks for your help in troubleshooting this.

### CODE REVIEW

**Comment by bodrovis** [comment]
I can confirm that this works for me as well. I'll release a new version soon. If someone else will have a problem similar to the one described here https://github.com/bodrovis/jquery-slick-rails/pull/13, more researching will be required.

**Comment by TechFounder** [comment]
For some reason when I tried to bundle the new version 1.5.8.2 i get ```Could not find a valid gem 'jquery-slick-rails-1.5.8.2' (>= 0) in any repository```

**Comment by bodrovis** [comment]
I tried installing it for this demo app https://github.com/bodrovis/jquery-slick-rails-demo and everything seems to be okay. It is still an issue?

**Comment by TechFounder** [comment]
Hum, yea, i tried to manually install the gem without any version and it kept installing the older version so I then tried it with a strict version number and was getting the error but now it seems to work. Thanks!

**Pull request merged**
